name: my_app
description: "ShartFlix"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  #Store
  flutter_secure_storage:
  shared_preferences:
  path_provider:
  #Bloc
  flutter_bloc:
  #Network
  retrofit: ^4.0.3
  dio: ^5.3.2
  json_annotation: ^4.9.0
  #Logger
  logger: ^2.0.2+1
  pretty_dio_logger:
    ^1.3.1
    #Router
  go_router:
    #Utilities
  permission_handler:
  intl_utils:
  equatable:
  photo_view: ^0.14.0
  #Dialog, etc
  cached_network_image: ^3.3.1
  another_flushbar: ^1.12.30
  loader_overlay:
    ^4.0.0
    #UI
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=2.3.0 <4.0.0"
  retrofit_generator: ^7.0.8
  json_serializable: ^6.6.2
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/png/
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arb_file: app_en.arb
  output_localization_file: app_localizations.dart
