name: my_app
description: "ShartFlix"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #Store
  flutter_secure_storage:
  shared_preferences:
  path_provider:
  #Bloc
  flutter_bloc:
  #Network
  retrofit: ^4.0.3
  dio: ^5.3.2
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^7.0.8
  build_runner: ">=2.3.0 <4.0.0"
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
